format:
	@rustup component add rustfmt
	cargo fmt

lint:
	cargo clippy

test:
	cargo test

build:
	cargo build --release

run:
	cargo run

clean:
	cargo clean

doc:
	cargo doc --no-deps

.PHONY: format lint test build run clean doc